INSERT INTO public.repter (varos, nev) VALUES ('Venustiano Carranza', 'Bentio Juárez nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Dubaj', 'Dubaji nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Billund', 'Billundi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Brno', 'Brno-Turany Havel repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('London', 'London-Heathrow-i repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Antalya', 'Antalyai repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Kolozsvár', 'Cluj Napoca nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Budapest', 'Budapest Ferihegyi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Helsinki', 'Helsinki-vantaa repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Firenze', 'Peretola repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Luxemburg', 'Findel repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Róma', 'Róma-Fiumicino nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Kastoria', 'Aristoteles repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Tel-Aviv', 'Ben-Gurion nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Kijev', 'Zhulyany repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Haarlemmermeer', 'Amszterdam-Schiphol repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Zakinthos', 'Zakinthosi nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Los Angeles', 'Los Angeles-i nemzetközi repuloter');
INSERT INTO public.repter (varos, nev) VALUES ('Frankfurt', 'Frankfurti repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Krakkó', 'John Paul II Balice nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Aarhus', 'Aarhusi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Katowice', 'Katowice Pyrzowice repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Delhi', 'Indira Gandhi nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Freising', 'Müncheni repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Dzsidda', 'Abdul-Aziz király nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Malaga', 'Málagai nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Temesvár', 'Temesvári nemzetközi repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Prága', 'Prága-Václav  repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Madrid', 'Adolfo Suárez Madrid-Barajas repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Milánó', 'Milánó-Malpensai repülőtér');
INSERT INTO public.repter (varos, nev) VALUES ('Párizs', 'Párizs-Charles de Gaulle repülőtér');
