INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L04', 'Utazó', 'Boeing 777', 300, 300, 'Hosszú távú nemzetközi utakra', 620);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L05', 'Felfedező', 'Boeing 787', 240, 240, 'Hosszú távú nemzetközi utakra', 650);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L25', 'Intelligens', 'Boeing 767-300ER', 290, 290, 'Közepes és hosszú távú utakra', 610);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L07', 'Kalandor', 'Boeing 747', 366, 366, 'Nagyon hosszú távú utakra', 720);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L27', 'Bájos', 'Boeing 757-200', 200, 200, 'Közepes távú utakra', 570);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L17', 'Ügyes', 'Boeing 737-800', 190, 190, 'Közepes távú utakra', 550);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L26', 'Erős', 'Airbus A310-300', 280, 280, 'Közepes távú utakra', 590);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L12', 'Gyorsaság', 'Airbus A340', 320, 320, 'Hosszú távú utakra', 640);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L03', 'Vándor', 'Airbus A330', 250, 250, 'Hosszú távú utakra', 600);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L21', 'Fényes', 'Boeing 777-300ER', 350, 350, 'Nagyon hosszú távú utakra', 740);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L20', 'Elegáns', 'Airbus A330neo', 260, 260, 'Hosszú távú utakra', 680);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L16', 'Szilárd', 'Airbus A319', 160, 160, 'Rövid távú utakra', 480);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L10', 'Sas', 'Airbus A310', 280, 280, 'Közepes távú utakra', 580);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L28', 'Szívós', 'Airbus A340-500', 320, 320, 'Hosszú távú utakra', 650);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L14', 'Álmodozó', 'Airbus A321', 220, 220, 'Rövid és közepes távú utakra', 520);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L19', 'Kitartó', 'Boeing 737-700', 140, 140, 'Rövid távú utakra', 460);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L29', 'Állhatatos', 'Boeing 737 MAX 8', 210, 210, 'Közepes távú utakra', 560);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L30', 'Bölcs', 'Airbus A321neo', 220, 220, 'Rövid és közepes távú utakra', 540);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L13', 'Bátor', 'Boeing 737 MAX', 210, 210, 'Közepes távú utakra', 540);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L24', 'Igényes', 'Airbus A350-1000', 350, 350, 'Hosszú távú nemzetközi utakra', 710);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L11', 'Páva', 'Boeing 757', 200, 200, 'Közepes távú utakra', 560);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L08', 'Hőstett', 'Airbus A350', 325, 325, 'Hosszú távú nemzetközi utakra', 680);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L09', 'Sólyom', 'Boeing 767', 290, 290, 'Közepes és hosszú távú utakra', 600);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L23', 'Merész', 'Boeing 747-8', 380, 380, 'Nagyon hosszú távú utakra', 730);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L15', 'Békés', 'Boeing 787-9', 250, 250, 'Hosszú távú nemzetközi utakra', 660);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L18', 'Előrelátó', 'Airbus A320neo', 180, 180, 'Rövid és közepes távú utakra', 530);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L22', 'Robusztus', 'Airbus A380plus', 550, 666, 'Nagyon hosszú távú utakra', 760);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L01', 'Pilóta', 'Airbus A320', 180, 200, 'Rövid távú utakra', 500);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L06', 'Turista', 'Airbus A380', 500, 540, 'Nagyon hosszú távú utakra', 700);
INSERT INTO public.repulo (lajstromjel, becenev, modell, ulohely, rakter, info, repultutakszama) VALUES ('HA-L02', 'Kapitány', 'Boeing 737', 190, 200, 'Közepes távú utakra', 550);
