INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (1, 285, 54000, true, 'Dzsidda');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (2, 325, 58000, false, 'Dzsidda');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (3, 860, 129000, true, 'Los Angeles');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (4, 785, 171000, false, 'Los Angeles');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (5, 310, 49000, true, 'Dubaj');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (6, 355, 37500, false, 'Dubaj');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (7, 160, 21000, true, 'London');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (8, 145, 13500, false, 'London');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (11, 130, 38000, true, 'Haarlemmermeer');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (12, 115, 34000, false, 'Haarlemmermeer');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (13, 105, 33000, true, 'Frankfurt');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (14, 95, 34000, false, 'Frankfurt');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (15, 610, 80000, true, 'Delhi');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (16, 630, 80000, false, 'Delhi');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (17, 925, 140000, true, 'Venustiano Carranza');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (18, 800, 240000, false, 'Venustiano Carranza');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (19, 75, 35000, true, 'Freising');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (20, 75, 32000, false, 'Freising');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (21, 45, 10000, true, 'Brno');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (22, 45, 13000, false, 'Brno');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (23, 140, 39000, true, 'Helsinki');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (24, 145, 31000, false, 'Helsinki');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (25, 215, 20000, true, 'Malaga');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (26, 205, 34000, false, 'Malaga');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (27, 180, 35000, true, 'Antalya');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (28, 200, 30000, false, 'Antalya');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (29, 200, 14000, true, 'Madrid');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (30, 190, 36000, false, 'Madrid');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (9, 140, 27000, true, 'Párizs');
INSERT INTO public.ut (id, hossz, ar, megy, repter_varos) VALUES (10, 130, 15000, false, 'Párizs');
